name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  build-test:
    runs-on: ubuntu-latest

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: |
          pnpm lint
          pnpm format:check
        env:
          SKIP_ENV_VALIDATION: true

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Run typecheck
        run: pnpm ts:check
